version: '3.8'

services:
  player-service:
    build:
      context: ./player-service
    ports:
      - "8002:8000"
    env_file:
      - ./player-service/.env
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env