name: tetris-royale-test
version: '3.8'

services:
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  auth-service:
    build: 
      context: ./auth-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres-test:5432/test_db
      - PLAYER_SERVICE_URL=http://player-service:8000
      - RATING_SERVICE_URL=http://rating-service:8000
      - SECRET_KEY=tGEepzjz3012ULhkFlf5DNow5atDzhEcqI5-tApfBUw
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test-network

  player-service:
    build:
      context: ./player-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres-test:5432/test_db
    depends_on:
      - postgres-test
    networks:
      - test-network

  rating-service:
    build:
      context: ./rating-service
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres-test:5432/test_db
    depends_on:
      - postgres-test
    networks:
      - test-network

networks:
  test-network:
    name: tetris-royale-test-network