version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
  player-service:
    build:
      context: ./player-service
    ports:
      - "8002:8000"
    env_file:
      - ./player-service/.env
    depends_on:
      - auth-service
  tournament-service:
    build:
      context: ./tournament-service
    ports:
      - "8003:8000"
    env_file:
      - ./tournament-service/.env
    depends_on:
      - auth-service
  matchmaking-service:
    build:
      context: ./matchmaking-service
    ports:
      - "8004:8000"
    env_file:
      - ./matchmaking-service/.env
    depends_on:
      - auth-service
